# Site
name: "imake-bhm"
title: "imake-bhm"
description: "iMake Innovation Center's Appreciation for Black History Month"
logo: 'assets/images/branding.png'
favicon: 'assets/images/branding.png'
baseurl: /imake-bhm
url: "https://imake-innovation-center.github.io/imake-bhm/"
# google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  jason:
    name: Jason Kennedy
    display_name: Jason Kennedy
    avatar: /assets/images/jason_kennedy.jpg

  anna:
    name: Anna Timarong
    display_name: Anna Timarong
    avatar: /assets/images/anna_timarong.png

  jeffery:
    name: Jeffery Dixon
    display_name: Jeffery Dixon
    avatar: /assets/images/jeffery_dixon.jpg

  nkeiru:
    name: Nkeiru Nkwocha
    display_name: Nkeiru Nkwocha
    avatar: /assets/images/nkeiru_nkwocha.png
    
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. 
# Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
